### ISSUE TITLE
DefaultSeo og:title and og:description only overridden by NextSeo when openGraph config provided

### ISSUE THREAD

**Issue by crosscompile** [garmeeh/next-seo#544] opened 2020-10-21 16:18 UTC
Hi!  First off, thank you so much for this library!

I noticed some unexpected behavior (not sure if it's a bug or intended) when using `DefaultSeo` and `NextSeo`.  The `DefaultSeo` `og:title` and `og:description` meta tags are not overridden by `NextSeo`'s `title` and `description` configurations unless an `openGraph` configuration object is provided to `NextSeo`.  I believe this is due to https://github.com/garmeeh/next-seo/blob/master/src/meta/buildTags.tsx#L152 evaluating as falsy in `NextSeo` so the `og:*` meta tags are never updated.

I've reproduced this behavior in the sandbox below where the `/` page does not successfully overwrite the meta tags while the `/about` page does.

https://codesandbox.io/s/serene-mcnulty-ofcu3

Let me know if anything else would be useful to debug!

**Comment by garmeeh** [comment] 2020-10-31 15:14
Hey @crosscompile yeah I think this is a bug alright. That top level check looks like a good candidate for the reason.

Maybe a simple fix would be to move title and description to be before this.

**Comment by sachdeva-shrey** [comment] 2020-12-11 15:36
Facing the same issue. Would be great if you could resolve this soon. Thanks!

**Comment by minseolee** [comment] 2021-04-19 08:21
Thanks a lot for helpful source code
Has this bug fixed?

**Comment by finnwoelm-sdsn** [comment] 2021-08-19 09:51
It's not yet fixed. Temporary workaround is to just provide an empty object to the `openGraph` property:


```js
<NextSeo title="My custom title" description="My custom description" openGraph={{}} />
```

This will overwrite/update the `og:title` and `og:description`, because `openGraph` will evaluate to `truthy` in `buildTags.tsx`:  https://github.com/garmeeh/next-seo/blob/420eb12ff7c6d2e15412d3bd09a0dca27863084f/src/meta/buildTags.tsx#L188

**Comment by sushantdhiman** [comment] 2021-09-01 11:49
I have submitted a fix for this issue here https://github.com/garmeeh/next-seo/pull/852, I hope it get merged soon

**Closed** 2021-09-16 19:43 UTC
Labels: bug, good first issue

**Comment by jordanlambrecht** [comment] 2022-06-21 20:18
I'm still experiencing this. If an OpenGraph image array is defined in DefaultSEO, it overrides individual pages' default images. Any updates?

**Comment by tobinbc** [comment] 2024-03-01 08:52
> I'm still experiencing this. If an OpenGraph image array is defined in DefaultSEO, it overrides individual pages' default images. Any updates?

I also have this and found a dumb solution (perhaps its by design); you need to define as many (or more) images in the `NextSeo.openGraph.images` as defined in `DefaultSeo.openGraph.images` to make Next SEO overwrite them. Not just the image url, but also the alt, and other fields.
I assume it's doing some sort of merge + overwrite with the 2 defined `openGraph.images` fields as rendered into the HTML, rather than overwriting the image field as defined in the React.

I'll update if I find a way to make it 'forget' the defaults.
